### ISSUE TITLE
Dont use transparency on System Settings control panel extensions

### ISSUE THREAD

**Issue by kekukui** [Guilouz/skin.estuary.mod.kodi18#3]
**Estuary Mod**
![screenshot000](https://user-images.githubusercontent.com/20834957/52322542-8a6a2480-29a7-11e9-9feb-4eb2a7833b25.png)

**Estuary**
![screenshot002](https://user-images.githubusercontent.com/20834957/52322552-90600580-29a7-11e9-8269-f8bd6074620f.png)

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.

**Comment by kekukui** [comment]
> I no longer use Kodi

Do you use some other program?  If so, which one do you recommend ?

**Comment by Guilouz** [comment]
> > I no longer use Kodi
> 
> Do you use some other program? If so, which one do you recommend ?

Yes I use Plex with server on my Synology NAS, player available on many devices (smart TV, Xbox, PS4/PS5, Android, iOS, macOS etc...) with similar functionnalities of Kodi like trailer, synopsys, multi scrapers etc... And you can also share your library with friends to play content remotly.
