### ISSUE TITLE
Dont use transparency on Skin Settings menu

### ISSUE THREAD

**Issue by kekukui** [Guilouz/skin.estuary.mod.kodi18#4]
**customize main menu**

![skin settings menu](https://user-images.githubusercontent.com/20834957/52519024-0cb24d00-2c23-11e9-9d51-d7b77a9bb8ff.png)

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
