### ISSUE TITLE
Remove Kodi logo

### ISSUE THREAD

**Issue by kekukui** [Guilouz/skin.estuary.mod.kodi18#5]
**Remove Kodi logo to make room for more menu items**

![remove kodi logo](https://user-images.githubusercontent.com/20834957/52521625-e18e2480-2c47-11e9-8f93-d46e99d8a4e9.png)

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
