### ISSUE TITLE
Display parent app icon on shortcuts in Favorites menu

### ISSUE THREAD

**Issue by kekukui** [Guilouz/skin.estuary.mod.kodi18#6]
**If a shortcut in the Favorites menu references a menu item within an add-on (such as a channel in the YouTube application), display an overlay icon that indicates which application the shortcut depends on.**

**Examples**
![favorite shortcut mockup 1](https://user-images.githubusercontent.com/20834957/52902832-68ad4080-31e4-11e9-8190-3b4101f8658b.png)   ![favorite shortcut mockup 2](https://user-images.githubusercontent.com/20834957/52902836-6fd44e80-31e4-11e9-9a1a-d40a06417d86.png)

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
