### ISSUE TITLE
latest channels in the tv tab doesn't show the channel name and current show

### ISSUE THREAD

**Issue by daggs1** [Guilouz/skin.estuary.mod.kodi18#7]
in the original Estuary skin, I can see the latest channels I've played listed in a square, within each square I can see listed the channel's name and current program.
the Estuary v2 mod doesn't show the same.
is it possible to match the behavior?

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
