### ISSUE TITLE
Unable to change skin colors

### ISSUE THREAD

**Issue by fOmey** [Guilouz/skin.estuary.mod.kodi18#8]
For some reason my menu highlight is now orange which makes white text difficult to read.

I assumed main color would change this, but it doesn't seem to be doing anything..  am I missing something?

**Comment by fOmey** [comment]
Fixed by installing skin color picker.. fluke I noticed it, maybe require the add-on to avoid confusion?

**Comment by fOmey** [comment]
Fixed by installing skin color picker.. fluke I noticed it, maybe require the add-on to avoid confusion?

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
